### ISSUE TITLE
Unexpected class java.lang.IllegalStateException

### ISSUE THREAD

**Issue by SammyForReal** [CCEmuX/CCEmuX#141] opened 2020-06-23 10:54 UTC
```
CCEmuX version: 1.0.0
OS name: Windows 10
OS version: 10.0
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 1.8.0_251
JRE architecture: 64

java.lang.IllegalStateException: Buffers have not been created
	at sun.awt.windows.WComponentPeer.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.getBackBuffer(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.flip(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.show(Unknown Source)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:52)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:264)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.lambda$advance$0(EmulatedComputerImpl.java:163)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.advance(EmulatedComputerImpl.java:163)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$3(CCEmuX.java:184)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:182)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:211)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:308)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by SquidDev** [comment] 2020-06-23 10:56
Duplicate of #61. This has been around for a while, but it's never been something we've been able to reproduce, let alone fix.

**Closed as completed by SquidDev** 2020-06-23 10:57 UTC
Labels: type: bug, resolution: duplicate, renderer: AWT
