### ISSUE TITLE
term.blit crashes CCEmuX with bad colors supplied

### ISSUE THREAD

**Issue by ghost** [CCEmuX/CCEmuX#73] opened 2017-08-05 20:11 UTC
Well, while I was experimenting with Lua, I found a bug. Luckily it isn't too too bad but, oh well.

**How to reproduce:**
- Run something along the lines of `term.blit("test","gggg","gggg")`
- Crashes CCEmuX with an ArrayIndexOutOfBounds exception.

Tested in Linux Mint 18.2 MATE on 4.10, using the latest git commit and the config tweaked for 5MB of storage. 

Stack trace:
```
OS name: Linux
OS version: 4.10.0-28-generic
OS architecture: amd64

JRE vendor: Oracle Corporation
JRE version: 1.8.0_131
JRE architecture: 64

Stack trace: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.clgd.ccemux.rendering.awt.TerminalComponent.drawChar(TerminalComponent.java:52)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.renderTerminal(TerminalComponent.java:86)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:114)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:164)
	at net.clgd.ccemux.emulation.EmulatedComputer.lambda$advance$0(EmulatedComputer.java:161)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.clgd.ccemux.emulation.EmulatedComputer.advance(EmulatedComputer.java:161)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$0(CCEmuX.java:125)
	at java.util.HashMap$KeySet.forEach(HashMap.java:932)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:123)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:148)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:86)

```

**Comment by dmarcuse** [comment] 2017-08-05 20:22
This is a duplicate of #66 and has already been fixed as of 7f94d79 on the 1.8 branch.

**Closed as completed by dmarcuse** 2017-08-05 20:22 UTC
Labels: resolution: duplicate

**Comment by dmarcuse** [comment] 2017-08-05 20:25
On a side note, if you switch to the 1.8 branch (which you should) you'll need to port your config - the config file is now `ccemux.json` and uses options listed [here](https://github.com/Lignum/CCEmuX/blob/1.8/src/main/resources/ccemux.json).

**Comment by ghost** [comment] 2017-08-05 20:26
Ah. Never seen that one (probably because of the title) but oh well. Thanks for telling me anyways!

**Comment by dmarcuse** [comment] 2017-08-05 20:28
Problem solved 😄
