### ISSUE TITLE
Screenshotting / GIF recording

### ISSUE THREAD

**Issue by znepb** [CCEmuX/CCEmuX#128] opened 2019-12-31 00:21 UTC
Just as the title says. A keybind or key (prntscreen) to save the screen to a file, or record a GIF.

**Comment by Lustyn** [comment] 2019-12-31 00:51
There are already [some tools](http://www.computercraft.info/forums2/index.php?/topic/24840-recgif/) made within ComputerCraft to achieve such a task. I'd say while it would be a nice feature, it's probably just not going to happen any time soon as no one has the interest to implement it directly in the emulator.

**Comment by SquidDev** [comment] 2019-12-31 07:00
Duplicate of #34. It's on my radar, I just hadn't worked out a nice way to expose it in in the API.

**Closed as completed** 2019-12-31 07:00 UTC
Labels: resolution: duplicate, type: enhancement, help wanted, type: discussion
