### ISSUE TITLE
[SUGGESTION] A Console-only Screen?

### ISSUE THREAD

**Issue by OfficialPixelBrush** [CCEmuX/CCEmuX#158] opened 2022-02-09 12:52 UTC
Basically start the Emulator in a standard CLI Window instead of the proprietary Renderer, coloring Characters with the equivalent Escape Codes etc. 

Would just be cool to have!

**Comment by Lustyn** [comment] 2022-02-18 06:08
Duplicate of #134

**Closed as completed by Lustyn** 2022-02-18 06:08 UTC
