### ISSUE TITLE
Unexpected class java.lang.IllegalStateException

### ISSUE THREAD

**Issue by LDDestroier** [CCEmuX/CCEmuX#121] opened 2018-12-22 23:50 UTC
```
CCEmuX version: 1.0.0
OS name: Linux
OS version: 4.18.0-13-generic
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 1.8.0_191
JRE architecture: 64

java.lang.IllegalStateException: Component must have a valid peer
	at java.awt.Component$FlipBufferStrategy.flip(Component.java:4092)
	at java.awt.Component$FlipBufferStrategy.show(Component.java:4213)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:162)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:279)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.lambda$advance$0(EmulatedComputerImpl.java:181)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at net.clgd.ccemux.emulation.EmulatedComputerImpl.advance(EmulatedComputerImpl.java:181)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$3(CCEmuX.java:187)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:185)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:214)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:265)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cc.emux.launcher.Launcher$main$emuThread$1.invoke(Launcher.kt:1103)
	at shadow.kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by dmarcuse** [comment] 2018-12-22 23:53
Duplicate of #61

**Closed as completed by dmarcuse** 2018-12-22 23:53 UTC

**Comment by SquidDev** [comment] 2018-12-23 15:00
That being said, if you know a way to reliably reproduce this, please do tell - it's something I've not been able to figure out.
