### ISSUE TITLE
Unexpected class java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Ale32bit** [CCEmuX/CCEmuX#90] opened 2018-02-24 14:57 UTC
```
CCEmuX version: 1.0-SNAPSHOT
OS name: Windows 10
OS version: 10.0
OS architecture: amd64
JRE vendor: Oracle Corporation
JRE version: 1.8.0_144
JRE architecture: 64

java.lang.IllegalStateException: Component must have a valid peer
	at java.awt.Component$FlipBufferStrategy.flip(Unknown Source)
	at java.awt.Component$FlipBufferStrategy.show(Unknown Source)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:150)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:259)
	at net.clgd.ccemux.emulation.EmulatedComputer.lambda$advance$0(EmulatedComputer.java:171)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.EmulatedComputer.advance(EmulatedComputer.java:171)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$2(CCEmuX.java:148)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:146)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:171)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:68)
```

**Comment by Lignum** [comment] 2018-02-24 15:35
Duplicate of #61.

**Closed as completed by Lignum** 2018-02-24 15:35 UTC
Labels: resolution: duplicate

**Comment by dmarcuse** [comment] 2018-02-24 16:19
Known issue with the AWT renderer, see #61. You can use the JFX renderer if it's a recurring issue.
