### ISSUE TITLE
Better documentation in the README or wiki on how plugins work.

### ISSUE THREAD

**Issue by MineRobber9000** [CCEmuX/CCEmuX#69] opened 2017-07-17 05:11 UTC
Namely, how to run CCEmuX with a plugin.

**Comment by dmarcuse** [comment] 2017-07-17 05:29
Duplicate of #53.

For plugins, run `emu data` and then put your plugins (or resource packs, if you want a custom terminal font) in the `plugins` folder.

**Closed as completed by dmarcuse** 2017-07-17 05:29 UTC
Labels: resolution: duplicate
